### ISSUE TITLE
Crash when clicking outside a selected quote

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#36]
```
java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 86]
at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4260)
at android.widget.Editor$HandleView.updatePosition(Editor.java:3708)
at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2507)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### Reproduce
1. Type a word
2. Select a word
3. Apply the quote formatting
4. Tap anywhere on the EditText
5. Crash

#### Tested
Emulator with Android 6.0

**Comment by 0nko** [comment]
Will be fixed by #24.
